# Seraph MCP — Pre-commit Hooks Configuration
#
# Enforces code quality standards before commits.
# Install: pre-commit install
# Run manually: pre-commit run --all-files

repos:
    # Ruff - Fast Python linter and formatter
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.8.4
      hooks:
          # Run the linter
          - id: ruff
            args: [--fix]
            stages: [pre-commit]
          # Run the formatter
          - id: ruff-format
            stages: [pre-commit]

    # Mypy - Static type checker
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.13.0
      hooks:
          - id: mypy
            args: [--config-file=pyproject.toml]
            additional_dependencies:
                - pydantic>=2.0.0
                - pydantic-settings>=2.0.0
                - types-redis>=4.6.0
                - types-cachetools>=5.3.0
                - fastmcp>=2.0.0
                - httpx>=0.25.0
                - redis>=5.0.0
                - cachetools>=5.3.0
                - openai>=1.0.0
                - anthropic>=0.25.0
                - google-genai>=0.2.0
                - tiktoken>=0.5.0
                - blake3>=1.0.7
                - pybreaker>=1.0.0
                - numpy
            stages: [pre-commit]
            exclude: ^(tests/|benchmarks/|src/semantic_cache/|src/context_optimization/seraph_compression\.py)

    # Basic file checks
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          # Prevent large files from being committed
          - id: check-added-large-files
            args: ["--maxkb=1000"]
            stages: [pre-commit]
          # Check for merge conflicts
          - id: check-merge-conflict
            stages: [pre-commit]
          # Check JSON files
          - id: check-json
            stages: [pre-commit]
          # Check TOML files
          - id: check-toml
            stages: [pre-commit]
          # Check YAML files
          - id: check-yaml
            args: ["--unsafe"] # Allow custom tags
            stages: [pre-commit]
          # Ensure files end with newline
          - id: end-of-file-fixer
            stages: [pre-commit]
          # Remove trailing whitespace
          - id: trailing-whitespace
            stages: [pre-commit]

# Configuration for specific hooks
default_language_version:
    python: python3.12

# Exclude patterns (applies to all hooks unless overridden)
exclude: |
    (?x)^(
        \.git/|
        \.github/|
        \.venv/|
        venv/|
        env/|
        __pycache__/|
        \.pytest_cache/|
        \.mypy_cache/|
        \.ruff_cache/|
        build/|
        dist/|
        .*\.egg-info/|
        uv\.lock$
    )

# Fail fast - stop after first failure
fail_fast: false

# Minimum pre-commit version
minimum_pre_commit_version: "3.0.0"
