# Seraph MCP — Pre-commit Hooks Configuration
#
# Enforces code quality standards before commits.
# Install: pre-commit install
# Run manually: pre-commit run --all-files

repos:
    # Ruff - Fast Python linter and formatter
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.6.0
      hooks:
          # Run the linter
          - id: ruff
            args: [--fix]
          # Run the formatter
          - id: ruff-format

    # Basic file checks
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          # Prevent large files from being committed
          - id: check-added-large-files
            args: ["--maxkb=1000"]
          # Check for merge conflicts
          - id: check-merge-conflict
          # Check JSON files
          - id: check-json
          # Check TOML files
          - id: check-toml
          # Check YAML files
          - id: check-yaml
            args: ["--unsafe"] # Allow custom tags
          # Ensure files end with newline
          - id: end-of-file-fixer
          # Remove trailing whitespace
          - id: trailing-whitespace

# Configuration for specific hooks
default_language_version:
    python: python3

# Exclude patterns (applies to all hooks unless overridden)
exclude: |
    (?x)^(
        \.git/|
        \.github/|
        \.venv/|
        venv/|
        env/|
        __pycache__/|
        \.pytest_cache/|
        \.mypy_cache/|
        \.ruff_cache/|
        build/|
        dist/|
        .*\.egg-info/|
        uv\.lock$
    )

# Fail fast - stop after first failure
fail_fast: false

# Minimum pre-commit version
minimum_pre_commit_version: "3.0.0"
