version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: seraph-redis-dev
    ports:
      - "6379:6379"   # Redis server
      - "8001:8001"   # RedisInsight UI
    volumes:
      - redis_dev_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_dev_data:
